// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFSS8QgQX3b7Lo_j-xPbhIM_61T1MbY24',
    appId: '1:549038065730:web:558002006e734359a745db',
    messagingSenderId: '549038065730',
    projectId: 'devmob-flutter-intra',
    authDomain: 'devmob-flutter-intra.firebaseapp.com',
    storageBucket: 'devmob-flutter-intra.appspot.com',
    measurementId: 'G-PEQM1EWDL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8GiPhRBJvsx9D3aUFhaOGaaFmdjwVmcE',
    appId: '1:549038065730:android:d2528cc6405fe1f0a745db',
    messagingSenderId: '549038065730',
    projectId: 'devmob-flutter-intra',
    storageBucket: 'devmob-flutter-intra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPkiahsF_lSIqmRCngIChmdL9yzChEC90',
    appId: '1:549038065730:ios:0071720f0019f30aa745db',
    messagingSenderId: '549038065730',
    projectId: 'devmob-flutter-intra',
    storageBucket: 'devmob-flutter-intra.firebasestorage.app',
    iosBundleId: 'com.example.devmobiFlutterIntra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPkiahsF_lSIqmRCngIChmdL9yzChEC90',
    appId: '1:549038065730:ios:0071720f0019f30aa745db',
    messagingSenderId: '549038065730',
    projectId: 'devmob-flutter-intra',
    storageBucket: 'devmob-flutter-intra.firebasestorage.app',
    iosBundleId: 'com.example.devmobiFlutterIntra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFSS8QgQX3b7Lo_j-xPbhIM_61T1MbY24',
    appId: '1:549038065730:web:e182251eae47522fa745db',
    messagingSenderId: '549038065730',
    projectId: 'devmob-flutter-intra',
    authDomain: 'devmob-flutter-intra.firebaseapp.com',
    storageBucket: 'devmob-flutter-intra.firebasestorage.app',
    measurementId: 'G-GE32D3GBGZ',
  );
}
